services:
  ollama:
    image: ollama/ollama:latest
    container_name: rag_ollama
    ports:
      - "11434:11434"
    volumes:
#      - ollama_data:/root/.ollama
      - /usr/share/ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rag_network

  chroma:
    image: chromadb/chroma:latest
    container_name: rag_chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rag_network

  streamlit:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: rag_streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
      - uploaded_docs:/app/uploaded_docs
    environment:
      - OLLAMA_URL=http://ollama:11434
      - CHROMA_URL=http://chroma:8000
    depends_on:
      ollama:
        condition: service_healthy
      chroma:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rag_network

volumes:
  ollama_data:
  chroma_data:
  uploaded_docs:

networks:
  rag_network:
    driver: bridge
